<?php

namespace App\Http\Requests;

use App\Models\User;
use Illuminate\Foundation\Http\FormRequest;

class registerStoreRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [

            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:' . User::class],
            'password' => ['required', \Illuminate\Validation\Rules\Password::default()],
            'age' => ['required', 'integer']
        ];
    }
    public function messages()
    {
        return [
            'name.required' =>'name is required',
            'email.email'=>'email invalid',
            'email.unique'=>'email exists',
            'password'=>'password invalid'
        ]; // TODO: Change the autogenerated stub
    }
}
