<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class usersCategoryRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'category'=>"required|exists:users,category",
//            'year'=>"required|exists:users,year",

            //
        ];
    }
    public function messages()
    {
        return [
            'category.required'=>'the category required',
//            'year.required'=>'the year required',
            'category.exists:users,category'=>'the category not exist',
//            'year.exists:users,year'=>'the year not exist',


        ]; // TODO: Change the autogenerated stub
    }
}
