<?php

namespace App\Http\Requests\livestream;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class storeLiveStreamRequset extends FormRequest
{
    protected $stopOnFirstFailure = true;

    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'description' => 'required',
            'title' => 'required',
//            'broadcaster_id' => 'required|exists:users,id',
            'subject' => 'required|exists:subjects,name',
            'year' => [
                'required',
                Rule::in([1, 2, 3, 4, 5]),
            ],
            //
        ];
    }


    public function messages()
    {
        return [
            'name.exists:subjects,name' => 'subject name is not valid',
            'name.required' => 'name of the subject is required',
//            'broadcaster_id.exists:users,id' => 'the broadcaster id is not valid',
            'year.required' => 'the year is required'
        ]; // TODO: Change the autogenerated stub
    }
}
